# The Docker image that will be used to build your app
image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r index.html public/  # Copy everything from repo root to 'public/'
    - cp -r MC_validation_plots public/
  artifacts:
    paths:
      - public
  only:
    - work  # Or 'master' if that's your branch
