{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Mon Dec 11 17:10:06 2023 by ROOT version6.26/10)
//   from TTree Events/Output tree
//   found on file: ZZTo4L_test.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *ifile_sig = (TFile*)gROOT->GetListOfFiles()->FindObject("HppMM500_001.root");
   TFile *ifile_bkg = (TFile*)gROOT->GetListOfFiles()->FindObject("ZZTo4L_test.root");

	TTree *tree_sig = (TTree*)ifile_sig->Get("Events");
	TTree *tree_bkg = (TTree*)ifile_bkg->Get("Events");
//Declaration of leaves types
   ULong64_t       run;
   ULong64_t       nElectron;
   ULong64_t       nMuon;
   ULong64_t       nTau;
   Int_t           lumi;
   ULong64_t       evt;
   Int_t           nPU;
   Int_t           nPUEOOT;
   Int_t           nPULOOT;
   Float_t         nPUtrue;
   Int_t           nPV;
   Int_t           nPVGood;
   Int_t           cat;
   Float_t         weight;
   Float_t         weightPU;
   Float_t         weightPUtrue;
   Float_t         LHEweight;
   Int_t           LHE_Njets;
   Float_t         LHEScaleWeights[9];
   Float_t         Generator_weight;
   Int_t           electronTriggerWord;
   Int_t           muonTriggerWord;
   Int_t           whichTriggerWord;
   Int_t           whichTriggerWordSubL;
   Int_t           nGoodElectron;
   Int_t           nGoodMuon;
   Int_t           GenPart_statusFlags_1;
   Int_t           GenPart_statusFlags_2;
   Int_t           GenPart_statusFlags_3;
   Int_t           GenPart_statusFlags_4;
   Int_t           GenPart_status_1;
   Int_t           GenPart_status_2;
   Int_t           GenPart_status_3;
   Int_t           GenPart_status_4;
   Float_t         pt_uncor_1;
   Float_t         pt_uncor_2;
   Float_t         pt_uncor_3;
   Float_t         pt_uncor_4;
   Float_t         m_uncor_1;
   Float_t         m_uncor_2;
   Float_t         m_uncor_3;
   Float_t         m_uncor_4;
   Float_t         pt_3;
   Float_t         pt_3_tr;
   Float_t         phi_3;
   Float_t         phi_3_tr;
   Float_t         eta_3;
   Float_t         eta_3_tr;
   Float_t         m_3;
   Float_t         q_3;
   Float_t         d0_3;
   Float_t         dZ_3;
   Float_t         mt_3;
   Float_t         pfmt_3;
   Float_t         iso_3;
   ULong64_t       gen_match_1;
   ULong64_t       gen_match_2;
   ULong64_t       gen_match_3;
   Float_t         isGlobal_3;
   Float_t         isTracker_3;
   Float_t         ip3d_3;
   Int_t           decayMode_3;
   Float_t         pt_4;
   Float_t         pt_4_tr;
   Float_t         phi_4;
   Float_t         phi_4_tr;
   Float_t         eta_4;
   Float_t         eta_4_tr;
   Float_t         m_4;
   Float_t         q_4;
   Float_t         d0_4;
   Float_t         dZ_4;
   Float_t         mt_4;
   Float_t         pfmt_4;
   Float_t         iso_4;
   ULong64_t       gen_match_4;
   Float_t         isGlobal_4;
   Float_t         isTracker_4;
   Float_t         ip3d_4;
   Int_t           decayMode_4;
   Float_t         pt_tt;
   Float_t         mt_tot;
   Float_t         m_vis;
   Float_t         m_sv;
   Float_t         mt_sv;
   Float_t         H_DR;
   Float_t         AMass;
   Float_t         H_LT;
   Float_t         dRl1H;
   Float_t         dRl2H;
   Float_t         dRlH;
   Float_t         dPhil1H;
   Float_t         dPhil2H;
   Float_t         dPhilH;
   Float_t         mll;
   Float_t         mll2;
   Float_t         Z_Pt;
   Float_t         Z_DR;
   Float_t         Z_SS;
   Float_t         pt_1;
   Float_t         m_1_tr;
   Float_t         pt_1_tr;
   Float_t         phi_1;
   Float_t         phi_1_tr;
   Float_t         eta_1;
   Float_t         eta_1_tr;
   Float_t         pt_2;
   Float_t         m_2_tr;
   Float_t         pt_2_tr;
   Float_t         phi_2;
   Float_t         phi_2_tr;
   Float_t         eta_2;
   Float_t         eta_2_tr;
   Float_t         iso_1;
   Float_t         iso_2;
   Float_t         q_1;
   Float_t         q_2;
   Float_t         L1PreFiringWeight_Nom;
   Float_t         L1PreFiringWeight_Up;
   Float_t         L1PreFiringWeight_Down;
   Float_t         d0_1;
   Float_t         dZ_1;
   Float_t         d0_2;
   Float_t         dZ_2;
   Float_t         isGlobal_1;
   Float_t         isGlobal_2;
   Float_t         isTracker_1;
   Float_t         isTracker_2;
   Float_t         MET_pt_UnclUp;
   Float_t         MET_phi_UnclUp;
   Float_t         MET_pt_UnclDown;
   Float_t         MET_phi_UnclDown;
   Float_t         met_UnclX;
   Float_t         met_UnclY;
   Float_t         MET_T1Smear_pt;
   Float_t         MET_T1Smear_phi;
   Float_t         met;
   Float_t         metphi;
   Float_t         metNoCor;
   Float_t         metphiNoCor;
   Float_t         metNoTauES;
   Float_t         metphiNoTauES;
   Float_t         metcov00;
   Float_t         metcov01;
   Float_t         metcov10;
   Float_t         metcov11;
   Float_t         isTrig_2;
   Float_t         isTrig_1;
   Float_t         isDoubleTrig;
   Float_t         njets;
   Float_t         nbtagL;
   Float_t         nbtagM;
   Float_t         nbtagT;
   ULong64_t       HTXS_Higgs_cat;
   Float_t         HTXS_Higgs_pt;
   Float_t         jflavour[12];
   Float_t         jeta[12];
   Float_t         jpt[12];
   Float_t         btagDeep[12];

   // Set branch addresses.
   Events->SetBranchAddress("run",&run);
   Events->SetBranchAddress("nElectron",&nElectron);
   Events->SetBranchAddress("nMuon",&nMuon);
   Events->SetBranchAddress("nTau",&nTau);
   Events->SetBranchAddress("lumi",&lumi);
   Events->SetBranchAddress("evt",&evt);
   Events->SetBranchAddress("nPU",&nPU);
   Events->SetBranchAddress("nPUEOOT",&nPUEOOT);
   Events->SetBranchAddress("nPULOOT",&nPULOOT);
   Events->SetBranchAddress("nPUtrue",&nPUtrue);
   Events->SetBranchAddress("nPV",&nPV);
   Events->SetBranchAddress("nPVGood",&nPVGood);
   Events->SetBranchAddress("cat",&cat);
   Events->SetBranchAddress("weight",&weight);
   Events->SetBranchAddress("weightPU",&weightPU);
   Events->SetBranchAddress("weightPUtrue",&weightPUtrue);
   Events->SetBranchAddress("LHEweight",&LHEweight);
   Events->SetBranchAddress("LHE_Njets",&LHE_Njets);
   Events->SetBranchAddress("LHEScaleWeights",LHEScaleWeights);
   Events->SetBranchAddress("Generator_weight",&Generator_weight);
   Events->SetBranchAddress("electronTriggerWord",&electronTriggerWord);
   Events->SetBranchAddress("muonTriggerWord",&muonTriggerWord);
   Events->SetBranchAddress("whichTriggerWord",&whichTriggerWord);
   Events->SetBranchAddress("whichTriggerWordSubL",&whichTriggerWordSubL);
   Events->SetBranchAddress("nGoodElectron",&nGoodElectron);
   Events->SetBranchAddress("nGoodMuon",&nGoodMuon);
   Events->SetBranchAddress("GenPart_statusFlags_1",&GenPart_statusFlags_1);
   Events->SetBranchAddress("GenPart_statusFlags_2",&GenPart_statusFlags_2);
   Events->SetBranchAddress("GenPart_statusFlags_3",&GenPart_statusFlags_3);
   Events->SetBranchAddress("GenPart_statusFlags_4",&GenPart_statusFlags_4);
   Events->SetBranchAddress("GenPart_status_1",&GenPart_status_1);
   Events->SetBranchAddress("GenPart_status_2",&GenPart_status_2);
   Events->SetBranchAddress("GenPart_status_3",&GenPart_status_3);
   Events->SetBranchAddress("GenPart_status_4",&GenPart_status_4);
   Events->SetBranchAddress("pt_uncor_1",&pt_uncor_1);
   Events->SetBranchAddress("pt_uncor_2",&pt_uncor_2);
   Events->SetBranchAddress("pt_uncor_3",&pt_uncor_3);
   Events->SetBranchAddress("pt_uncor_4",&pt_uncor_4);
   Events->SetBranchAddress("m_uncor_1",&m_uncor_1);
   Events->SetBranchAddress("m_uncor_2",&m_uncor_2);
   Events->SetBranchAddress("m_uncor_3",&m_uncor_3);
   Events->SetBranchAddress("m_uncor_4",&m_uncor_4);
   Events->SetBranchAddress("pt_3",&pt_3);
   Events->SetBranchAddress("pt_3_tr",&pt_3_tr);
   Events->SetBranchAddress("phi_3",&phi_3);
   Events->SetBranchAddress("phi_3_tr",&phi_3_tr);
   Events->SetBranchAddress("eta_3",&eta_3);
   Events->SetBranchAddress("eta_3_tr",&eta_3_tr);
   Events->SetBranchAddress("m_3",&m_3);
   Events->SetBranchAddress("q_3",&q_3);
   Events->SetBranchAddress("d0_3",&d0_3);
   Events->SetBranchAddress("dZ_3",&dZ_3);
   Events->SetBranchAddress("mt_3",&mt_3);
   Events->SetBranchAddress("pfmt_3",&pfmt_3);
   Events->SetBranchAddress("iso_3",&iso_3);
   Events->SetBranchAddress("gen_match_1",&gen_match_1);
   Events->SetBranchAddress("gen_match_2",&gen_match_2);
   Events->SetBranchAddress("gen_match_3",&gen_match_3);
   Events->SetBranchAddress("isGlobal_3",&isGlobal_3);
   Events->SetBranchAddress("isTracker_3",&isTracker_3);
   Events->SetBranchAddress("ip3d_3",&ip3d_3);
   Events->SetBranchAddress("decayMode_3",&decayMode_3);
   Events->SetBranchAddress("pt_4",&pt_4);
   Events->SetBranchAddress("pt_4_tr",&pt_4_tr);
   Events->SetBranchAddress("phi_4",&phi_4);
   Events->SetBranchAddress("phi_4_tr",&phi_4_tr);
   Events->SetBranchAddress("eta_4",&eta_4);
   Events->SetBranchAddress("eta_4_tr",&eta_4_tr);
   Events->SetBranchAddress("m_4",&m_4);
   Events->SetBranchAddress("q_4",&q_4);
   Events->SetBranchAddress("d0_4",&d0_4);
   Events->SetBranchAddress("dZ_4",&dZ_4);
   Events->SetBranchAddress("mt_4",&mt_4);
   Events->SetBranchAddress("pfmt_4",&pfmt_4);
   Events->SetBranchAddress("iso_4",&iso_4);
   Events->SetBranchAddress("gen_match_4",&gen_match_4);
   Events->SetBranchAddress("isGlobal_4",&isGlobal_4);
   Events->SetBranchAddress("isTracker_4",&isTracker_4);
   Events->SetBranchAddress("ip3d_4",&ip3d_4);
   Events->SetBranchAddress("decayMode_4",&decayMode_4);
   Events->SetBranchAddress("pt_tt",&pt_tt);
   Events->SetBranchAddress("mt_tot",&mt_tot);
   Events->SetBranchAddress("m_vis",&m_vis);
   Events->SetBranchAddress("m_sv",&m_sv);
   Events->SetBranchAddress("mt_sv",&mt_sv);
   Events->SetBranchAddress("H_DR",&H_DR);
   Events->SetBranchAddress("AMass",&AMass);
   Events->SetBranchAddress("H_LT",&H_LT);
   Events->SetBranchAddress("dRl1H",&dRl1H);
   Events->SetBranchAddress("dRl2H",&dRl2H);
   Events->SetBranchAddress("dRlH",&dRlH);
   Events->SetBranchAddress("dPhil1H",&dPhil1H);
   Events->SetBranchAddress("dPhil2H",&dPhil2H);
   Events->SetBranchAddress("dPhilH",&dPhilH);
   Events->SetBranchAddress("mll",&mll);
   Events->SetBranchAddress("mll2",&mll2);
   Events->SetBranchAddress("Z_Pt",&Z_Pt);
   Events->SetBranchAddress("Z_DR",&Z_DR);
   Events->SetBranchAddress("Z_SS",&Z_SS);
   Events->SetBranchAddress("pt_1",&pt_1);
   Events->SetBranchAddress("m_1_tr",&m_1_tr);
   Events->SetBranchAddress("pt_1_tr",&pt_1_tr);
   Events->SetBranchAddress("phi_1",&phi_1);
   Events->SetBranchAddress("phi_1_tr",&phi_1_tr);
   Events->SetBranchAddress("eta_1",&eta_1);
   Events->SetBranchAddress("eta_1_tr",&eta_1_tr);
   Events->SetBranchAddress("pt_2",&pt_2);
   Events->SetBranchAddress("m_2_tr",&m_2_tr);
   Events->SetBranchAddress("pt_2_tr",&pt_2_tr);
   Events->SetBranchAddress("phi_2",&phi_2);
   Events->SetBranchAddress("phi_2_tr",&phi_2_tr);
   Events->SetBranchAddress("eta_2",&eta_2);
   Events->SetBranchAddress("eta_2_tr",&eta_2_tr);
   Events->SetBranchAddress("iso_1",&iso_1);
   Events->SetBranchAddress("iso_2",&iso_2);
   Events->SetBranchAddress("q_1",&q_1);
   Events->SetBranchAddress("q_2",&q_2);
   Events->SetBranchAddress("L1PreFiringWeight_Nom",&L1PreFiringWeight_Nom);
   Events->SetBranchAddress("L1PreFiringWeight_Up",&L1PreFiringWeight_Up);
   Events->SetBranchAddress("L1PreFiringWeight_Down",&L1PreFiringWeight_Down);
   Events->SetBranchAddress("d0_1",&d0_1);
   Events->SetBranchAddress("dZ_1",&dZ_1);
   Events->SetBranchAddress("d0_2",&d0_2);
   Events->SetBranchAddress("dZ_2",&dZ_2);
   Events->SetBranchAddress("isGlobal_1",&isGlobal_1);
   Events->SetBranchAddress("isGlobal_2",&isGlobal_2);
   Events->SetBranchAddress("isTracker_1",&isTracker_1);
   Events->SetBranchAddress("isTracker_2",&isTracker_2);
   Events->SetBranchAddress("MET_pt_UnclUp",&MET_pt_UnclUp);
   Events->SetBranchAddress("MET_phi_UnclUp",&MET_phi_UnclUp);
   Events->SetBranchAddress("MET_pt_UnclDown",&MET_pt_UnclDown);
   Events->SetBranchAddress("MET_phi_UnclDown",&MET_phi_UnclDown);
   Events->SetBranchAddress("met_UnclX",&met_UnclX);
   Events->SetBranchAddress("met_UnclY",&met_UnclY);
   Events->SetBranchAddress("MET_T1Smear_pt",&MET_T1Smear_pt);
   Events->SetBranchAddress("MET_T1Smear_phi",&MET_T1Smear_phi);
   Events->SetBranchAddress("met",&met);
   Events->SetBranchAddress("metphi",&metphi);
   Events->SetBranchAddress("metNoCor",&metNoCor);
   Events->SetBranchAddress("metphiNoCor",&metphiNoCor);
   Events->SetBranchAddress("metNoTauES",&metNoTauES);
   Events->SetBranchAddress("metphiNoTauES",&metphiNoTauES);
   Events->SetBranchAddress("metcov00",&metcov00);
   Events->SetBranchAddress("metcov01",&metcov01);
   Events->SetBranchAddress("metcov10",&metcov10);
   Events->SetBranchAddress("metcov11",&metcov11);
   Events->SetBranchAddress("isTrig_2",&isTrig_2);
   Events->SetBranchAddress("isTrig_1",&isTrig_1);
   Events->SetBranchAddress("isDoubleTrig",&isDoubleTrig);
   Events->SetBranchAddress("njets",&njets);
   Events->SetBranchAddress("nbtagL",&nbtagL);
   Events->SetBranchAddress("nbtagM",&nbtagM);
   Events->SetBranchAddress("nbtagT",&nbtagT);
   Events->SetBranchAddress("HTXS_Higgs_cat",&HTXS_Higgs_cat);
   Events->SetBranchAddress("HTXS_Higgs_pt",&HTXS_Higgs_pt);
   Events->SetBranchAddress("jflavour",jflavour);
   Events->SetBranchAddress("jeta",jeta);
   Events->SetBranchAddress("jpt",jpt);
   Events->SetBranchAddress("btagDeep",btagDeep);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// Events->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = tree_bkg->GetEntries();

   for (Long64_t i=0; i<nentries;i++) {
     std::cout<< i <<std::endl; 
   }
}