#include <TTree.h>
#include <TH1F.h>
#include <TCanvas.h>

//////////////////////////////////////////////////////////
// Made using tree->MakeClass("MyBranch"); Creates MyBranch.C and MyBranch.h 
//This file has been automatically generated 
//  (Mon Dec 11 17:10:06 2023 by ROOT version6.26/10)
//from TTree tree/Output tree
//found on file: ZZTo4L_test.root
//////////////////////////////////////////////////////////
   // Declaration of leaf types
   ULong64_t       run;
   ULong64_t       nElectron;
   ULong64_t       nMuon;
   ULong64_t       nTau;
   Int_t           lumi;
   ULong64_t       evt;
   Int_t           nPU;
   Int_t           nPUEOOT;
   Int_t           nPULOOT;
   Double_t        nPUtrue;
   Int_t           nPV;
   Int_t           nPVGood;
   Int_t           cat;
   Int_t           gen_cat;
   Double_t        brWeight;
   Double_t        weight;
   Double_t        weightPU;
   Double_t        weightPUtrue;
   Double_t        weightPUtruejson;
   Double_t        weightPUtruejson_up;
   Double_t        weightPUtruejson_down;
   Double_t        LHEweight;
   Int_t           LHE_Njets;
   Double_t        LHEScaleWeights[9];
   Double_t        Generator_weight;
   Int_t           electronTriggerWord;
   Int_t           muonTriggerWord;
   Int_t           whichTriggerWord;
   Int_t           whichTriggerWordSubL;
   Double_t        IDSF_1;
   Double_t        ISOSF_1;
   Double_t        TrigSF_1;
   Double_t        IDSF_2;
   Double_t        ISOSF_2;
   Double_t        TrigSF_2;
   Double_t        IDSF_3;
   Double_t        ISOSF_3;
   Double_t        TrigSF_3;
   Double_t        IDSF_4;
   Double_t        ISOSF_4;
   Double_t        TrigSF_4;
   Double_t        EleID_1;
   Double_t        EleID_2;
   Double_t        EleID_3;
   Double_t        EleID_4;
   Int_t           MuID_1;
   Int_t           MuID_2;
   Int_t           MuID_3;
   Int_t           MuID_4;
   Double_t        TauVsEleIDSF_1;
   Double_t        TauVsEleIDSF_2;
   Double_t        TauVsEleIDSF_3;
   Double_t        TauVsEleIDSF_4;
   Double_t        TauVsMuIDSF_1;
   Double_t        TauVsMuIDSF_2;
   Double_t        TauVsMuIDSF_3;
   Double_t        TauVsMuIDSF_4;
   Double_t        TauVsJetIDSF_1;
   Double_t        TauVsJetIDSF_2;
   Double_t        TauVsJetIDSF_3;
   Double_t        TauVsJetIDSF_4;
   Double_t        TauES_1;
   Double_t        TauES_2;
   Double_t        TauES_3;
   Double_t        TauES_4;
   Int_t           nGoodElectron;
   Int_t           nGoodMuon;
   Int_t           nGoodTau;
   Int_t           GenPart_statusFlags_1;
   Int_t           GenPart_statusFlags_2;
   Int_t           GenPart_statusFlags_3;
   Int_t           GenPart_statusFlags_4;
   Int_t           GenPart_status_1;
   Int_t           GenPart_status_2;
   Int_t           GenPart_status_3;
   Int_t           GenPart_status_4;
   Double_t        pt_uncor_1;
   Double_t        pt_uncor_2;
   Double_t        pt_uncor_3;
   Double_t        pt_uncor_4;
   Double_t        m_uncor_1;
   Double_t        m_uncor_2;
   Double_t        m_uncor_3;
   Double_t        m_uncor_4;
   Double_t        pt_3;
   Double_t        pt_3_tr;
   Double_t        phi_3;
   Double_t        phi_3_tr;
   Double_t        eta_3;
   Double_t        eta_3_tr;
   Double_t        m_3;
   Double_t        q_3;
   Double_t        d0_3;
   Double_t        dZ_3;
   Double_t        mt_3;
   Double_t        pfmt_3;
   Double_t        iso_3;
   ULong64_t       gen_match_1;
   ULong64_t       gen_match_2;
   ULong64_t       gen_match_3;
   Double_t        isGlobal_3;
   Double_t        isTracker_3;
   Double_t        ip3d_3;
   Int_t           decayMode_3;
   Int_t           decayMode_4;
   Double_t        pt_4;
   Double_t        pt_4_tr;
   Double_t        phi_4;
   Double_t        phi_4_tr;
   Double_t        eta_4;
   Double_t        eta_4_tr;
   Double_t        m_4;
   Double_t        q_4;
   Double_t        d0_4;
   Double_t        dZ_4;
   Double_t        mt_4;
   Double_t        pfmt_4;
   Double_t        iso_4;
   ULong64_t       gen_match_4;
   Double_t        isGlobal_4;
   Double_t        isTracker_4;
   Double_t        ip3d_4;
   Int_t           decayMode_1;
   Int_t           decayMode_2;
   Double_t        pt_tt;
   Double_t        mt_tot;
   Double_t        m_vis;
   Double_t        mDCH1_sv;
   Double_t        mtDCH1_sv;
   Double_t        mDCH2_sv;
   Double_t        mtDCH2_sv;
   Double_t        mDCH1_sv4;
   Double_t        mtDCH1_sv4;
   Double_t        mDCH2_sv4;
   Double_t        mtDCH2_sv4;
   Double_t        H_DR;
   Double_t        AMass;
   Double_t        H_LT;
   Double_t        dRl1H;
   Double_t        dRl2H;
   Double_t        dRlH;
   Double_t        dPhil1H;
   Double_t        dPhil2H;
   Double_t        dPhilH;
   Double_t        mll;
   Double_t        mll2;
   Double_t        Z_Pt;
   Double_t        Z_DR;
   Double_t        Z_SS;
   Double_t        pt_1;
   Double_t        m_1;
   Double_t        m_1_tr;
   Double_t        pt_1_tr;
   Double_t        phi_1;
   Double_t        phi_1_tr;
   Double_t        eta_1;
   Double_t        eta_1_tr;
   Double_t        pt_2;
   Double_t        m_2;
   Double_t        m_2_tr;
   Double_t        pt_2_tr;
   Double_t        phi_2;
   Double_t        phi_2_tr;
   Double_t        eta_2;
   Double_t        eta_2_tr;
   Double_t        iso_1;
   Double_t        iso_2;
   Double_t        q_1;
   Double_t        q_2;
   Double_t        L1PreFiringWeight_Nom;
   Double_t        L1PreFiringWeight_Up;
   Double_t        L1PreFiringWeight_Down;
   Double_t        d0_1;
   Double_t        dZ_1;
   Double_t        d0_2;
   Double_t        dZ_2;
   Double_t        isGlobal_1;
   Double_t        isGlobal_2;
   Double_t        isTracker_1;
   Double_t        isTracker_2;
   Double_t        MET_pt_UnclUp;
   Double_t        MET_phi_UnclUp;
   Double_t        MET_pt_UnclDown;
   Double_t        MET_phi_UnclDown;
   Double_t        met_UnclX;
   Double_t        met_UnclY;
   Double_t        MET_T1Smear_pt;
   Double_t        MET_T1Smear_phi;
   Double_t        met;
   Double_t        metphi;
   Double_t        metNoCor;
   Double_t        metphiNoCor;
   Double_t        metNoTauES;
   Double_t        metphiNoTauES;
   Double_t        metcov00;
   Double_t        metcov01;
   Double_t        metcov10;
   Double_t        metcov11;
   Double_t        isTrig_2;
   Double_t        isTrig_1;
   Double_t        isDoubleTrig;
   Double_t        njets;
   Double_t        nbtagL;
   Double_t        nbtagM;
   Double_t        nbtagT;
   ULong64_t       HTXS_Higgs_cat;
   Double_t        HTXS_Higgs_pt;
   Double_t        jflavour[12];
   Double_t        jeta[12];
   Double_t        jpt[12];
   Double_t        btagDeep[12];
   
void MyBranch(TTree* tree){	

	// Set branch addresses.
	tree->SetBranchAddress("run",&run);
	tree->SetBranchAddress("nElectron",&nElectron);
	tree->SetBranchAddress("nMuon",&nMuon);
	tree->SetBranchAddress("nTau",&nTau);
	tree->SetBranchAddress("lumi",&lumi);
	tree->SetBranchAddress("evt",&evt);
	tree->SetBranchAddress("nPU",&nPU);
	tree->SetBranchAddress("nPUEOOT",&nPUEOOT);
	tree->SetBranchAddress("nPULOOT",&nPULOOT);
	tree->SetBranchAddress("nPUtrue",&nPUtrue);
	tree->SetBranchAddress("nPV",&nPV);
	tree->SetBranchAddress("nPVGood",&nPVGood);
	tree->SetBranchAddress("cat",&cat);
	tree->SetBranchAddress("gen_cat",&gen_cat);
	tree->SetBranchAddress("brWeight",&brWeight);
	tree->SetBranchAddress("weight",&weight);
	tree->SetBranchAddress("weightPU",&weightPU);
	tree->SetBranchAddress("weightPUtrue",&weightPUtrue);
	tree->SetBranchAddress("weightPUtruejson",&weightPUtruejson);
	tree->SetBranchAddress("weightPUtruejson_up", &weightPUtruejson_up);
	tree->SetBranchAddress("weightPUtruejson_down", &weightPUtruejson_down);
	//tree->SetBranchAddress("LHEweight",&LHEweight);
	//tree->SetBranchAddress("LHE_Njets",&LHE_Njets);
	
	tree->SetBranchAddress("IDSF_1", &IDSF_1);
	tree->SetBranchAddress("ISOSF_1", &ISOSF_1);
	tree->SetBranchAddress("TrigSF_1", &TrigSF_1);
	tree->SetBranchAddress("IDSF_2", &IDSF_2);
	tree->SetBranchAddress("ISOSF_2", &ISOSF_2);
	tree->SetBranchAddress("TrigSF_2", &TrigSF_2);
	tree->SetBranchAddress("IDSF_3", &IDSF_3);
	tree->SetBranchAddress("ISOSF_3", &ISOSF_3);
	tree->SetBranchAddress("TrigSF_3", &TrigSF_3);
	tree->SetBranchAddress("IDSF_4", &IDSF_4);
	tree->SetBranchAddress("ISOSF_4", &ISOSF_4);
	tree->SetBranchAddress("TrigSF_4", &TrigSF_4);
    tree->SetBranchAddress("EleID_1", &EleID_1);
    tree->SetBranchAddress("EleID_2", &EleID_2);
    tree->SetBranchAddress("EleID_3", &EleID_3);
    tree->SetBranchAddress("EleID_4", &EleID_4);
    tree->SetBranchAddress("MuID_1", &MuID_1);
    tree->SetBranchAddress("MuID_2", &MuID_2);
    tree->SetBranchAddress("MuID_3", &MuID_3);
    tree->SetBranchAddress("MuID_4", &MuID_4);
    tree->SetBranchAddress("TauVsEleIDSF_1", &TauVsEleIDSF_1);
    tree->SetBranchAddress("TauVsEleIDSF_2", &TauVsEleIDSF_2);
    tree->SetBranchAddress("TauVsEleIDSF_3", &TauVsEleIDSF_3);
    tree->SetBranchAddress("TauVsEleIDSF_4", &TauVsEleIDSF_4);
    tree->SetBranchAddress("TauVsMuIDSF_1", &TauVsMuIDSF_1);
    tree->SetBranchAddress("TauVsMuIDSF_2", &TauVsMuIDSF_2);
    tree->SetBranchAddress("TauVsMuIDSF_3", &TauVsMuIDSF_3);
    tree->SetBranchAddress("TauVsMuIDSF_4", &TauVsMuIDSF_4);
    tree->SetBranchAddress("TauVsJetIDSF_1", &TauVsJetIDSF_1);
    tree->SetBranchAddress("TauVsJetIDSF_2", &TauVsJetIDSF_2);
    tree->SetBranchAddress("TauVsJetIDSF_3", &TauVsJetIDSF_3);
    tree->SetBranchAddress("TauVsJetIDSF_4", &TauVsJetIDSF_4);
    tree->SetBranchAddress("TauES_1", &TauES_1);
    tree->SetBranchAddress("TauES_2", &TauES_2);
    tree->SetBranchAddress("TauES_3", &TauES_3);
    tree->SetBranchAddress("TauES_4", &TauES_4);
	tree->SetBranchAddress("LHEScaleWeights",LHEScaleWeights);
	tree->SetBranchAddress("Generator_weight",&Generator_weight);
	tree->SetBranchAddress("electronTriggerWord",&electronTriggerWord);
	tree->SetBranchAddress("muonTriggerWord",&muonTriggerWord);
	tree->SetBranchAddress("whichTriggerWord",&whichTriggerWord);
	tree->SetBranchAddress("whichTriggerWordSubL",&whichTriggerWordSubL);
	tree->SetBranchAddress("nGoodElectron",&nGoodElectron);
	tree->SetBranchAddress("nGoodMuon",&nGoodMuon);
	tree->SetBranchAddress("GenPart_statusFlags_1",&GenPart_statusFlags_1);
	tree->SetBranchAddress("GenPart_statusFlags_2",&GenPart_statusFlags_2);
	tree->SetBranchAddress("GenPart_statusFlags_3",&GenPart_statusFlags_3);
	tree->SetBranchAddress("GenPart_statusFlags_4",&GenPart_statusFlags_4);
	tree->SetBranchAddress("GenPart_status_1",&GenPart_status_1);
	tree->SetBranchAddress("GenPart_status_2",&GenPart_status_2);
	tree->SetBranchAddress("GenPart_status_3",&GenPart_status_3);
	tree->SetBranchAddress("GenPart_status_4",&GenPart_status_4);
	tree->SetBranchAddress("pt_uncor_1",&pt_uncor_1);
	tree->SetBranchAddress("pt_uncor_2",&pt_uncor_2);
	tree->SetBranchAddress("pt_uncor_3",&pt_uncor_3);
	tree->SetBranchAddress("pt_uncor_4",&pt_uncor_4);
	tree->SetBranchAddress("m_uncor_1",&m_uncor_1);
	tree->SetBranchAddress("m_uncor_2",&m_uncor_2);
	tree->SetBranchAddress("m_uncor_3",&m_uncor_3);
	tree->SetBranchAddress("m_uncor_4",&m_uncor_4);
	tree->SetBranchAddress("pt_3",&pt_3);
	tree->SetBranchAddress("pt_3_tr",&pt_3_tr);
	tree->SetBranchAddress("phi_3",&phi_3);
	tree->SetBranchAddress("phi_3_tr",&phi_3_tr);
	tree->SetBranchAddress("eta_3",&eta_3);
	tree->SetBranchAddress("eta_3_tr",&eta_3_tr);
	tree->SetBranchAddress("m_3",&m_3);
	tree->SetBranchAddress("q_3",&q_3);
	tree->SetBranchAddress("d0_3",&d0_3);
	tree->SetBranchAddress("dZ_3",&dZ_3);
	tree->SetBranchAddress("mt_3",&mt_3);
	tree->SetBranchAddress("pfmt_3",&pfmt_3);
	tree->SetBranchAddress("iso_3",&iso_3);
	tree->SetBranchAddress("gen_match_1",&gen_match_1);
	tree->SetBranchAddress("gen_match_2",&gen_match_2);
	tree->SetBranchAddress("gen_match_3",&gen_match_3);
	tree->SetBranchAddress("isGlobal_3",&isGlobal_3);
	tree->SetBranchAddress("isTracker_3",&isTracker_3);
	tree->SetBranchAddress("ip3d_3",&ip3d_3);
	tree->SetBranchAddress("decayMode_3",&decayMode_3);
	tree->SetBranchAddress("pt_4",&pt_4);
	tree->SetBranchAddress("pt_4_tr",&pt_4_tr);
	tree->SetBranchAddress("phi_4",&phi_4);
	tree->SetBranchAddress("phi_4_tr",&phi_4_tr);
	tree->SetBranchAddress("eta_4",&eta_4);
	tree->SetBranchAddress("eta_4_tr",&eta_4_tr);
	tree->SetBranchAddress("m_4",&m_4);
	tree->SetBranchAddress("q_4",&q_4);
	tree->SetBranchAddress("d0_4",&d0_4);
	tree->SetBranchAddress("dZ_4",&dZ_4);
	tree->SetBranchAddress("mt_4",&mt_4);
	tree->SetBranchAddress("pfmt_4",&pfmt_4);
	tree->SetBranchAddress("iso_4",&iso_4);
	tree->SetBranchAddress("gen_match_4",&gen_match_4);
	tree->SetBranchAddress("isGlobal_4",&isGlobal_4);
	tree->SetBranchAddress("isTracker_4",&isTracker_4);
	tree->SetBranchAddress("ip3d_4",&ip3d_4);
	tree->SetBranchAddress("decayMode_4",&decayMode_4);
	tree->SetBranchAddress("pt_tt",&pt_tt);
	tree->SetBranchAddress("mt_tot",&mt_tot);
	tree->SetBranchAddress("m_vis",&m_vis);
	//tree->SetBranchAddress("m_sv",&m_sv);
	//tree->SetBranchAddress("mt_sv",&mt_sv);
	tree->SetBranchAddress("H_DR",&H_DR);
	tree->SetBranchAddress("AMass",&AMass);
	tree->SetBranchAddress("H_LT",&H_LT);
	tree->SetBranchAddress("dRl1H",&dRl1H);
	tree->SetBranchAddress("dRl2H",&dRl2H);
	tree->SetBranchAddress("dRlH",&dRlH);
	tree->SetBranchAddress("dPhil1H",&dPhil1H);
	tree->SetBranchAddress("dPhil2H",&dPhil2H);
	tree->SetBranchAddress("dPhilH",&dPhilH);
	tree->SetBranchAddress("mll",&mll);
	tree->SetBranchAddress("mll2",&mll2);
	tree->SetBranchAddress("Z_Pt",&Z_Pt);
	tree->SetBranchAddress("Z_DR",&Z_DR);
	tree->SetBranchAddress("Z_SS",&Z_SS);
	tree->SetBranchAddress("pt_1",&pt_1);
	tree->SetBranchAddress("m_1_tr",&m_1_tr);
	tree->SetBranchAddress("m_1",&m_1);
	tree->SetBranchAddress("m_2",&m_2);
	tree->SetBranchAddress("pt_1_tr",&pt_1_tr);
	tree->SetBranchAddress("phi_1",&phi_1);
	tree->SetBranchAddress("phi_1_tr",&phi_1_tr);
	tree->SetBranchAddress("eta_1",&eta_1);
	tree->SetBranchAddress("eta_1_tr",&eta_1_tr);
	tree->SetBranchAddress("pt_2",&pt_2);
	tree->SetBranchAddress("m_2_tr",&m_2_tr);
	tree->SetBranchAddress("pt_2_tr",&pt_2_tr);
	tree->SetBranchAddress("phi_2",&phi_2);
	tree->SetBranchAddress("phi_2_tr",&phi_2_tr);
	tree->SetBranchAddress("eta_2",&eta_2);
	tree->SetBranchAddress("eta_2_tr",&eta_2_tr);
	tree->SetBranchAddress("iso_1",&iso_1);
	tree->SetBranchAddress("iso_2",&iso_2);
	tree->SetBranchAddress("q_1",&q_1);
	tree->SetBranchAddress("q_2",&q_2);
	tree->SetBranchAddress("L1PreFiringWeight_Nom",&L1PreFiringWeight_Nom);
	tree->SetBranchAddress("L1PreFiringWeight_Up",&L1PreFiringWeight_Up);
	tree->SetBranchAddress("L1PreFiringWeight_Down",&L1PreFiringWeight_Down);
	tree->SetBranchAddress("d0_1",&d0_1);
	tree->SetBranchAddress("dZ_1",&dZ_1);
	tree->SetBranchAddress("d0_2",&d0_2);
	tree->SetBranchAddress("dZ_2",&dZ_2);
	tree->SetBranchAddress("isGlobal_1",&isGlobal_1);
	tree->SetBranchAddress("isGlobal_2",&isGlobal_2);
	tree->SetBranchAddress("isTracker_1",&isTracker_1);
	tree->SetBranchAddress("isTracker_2",&isTracker_2);
	tree->SetBranchAddress("MET_pt_UnclUp",&MET_pt_UnclUp);
	tree->SetBranchAddress("MET_phi_UnclUp",&MET_phi_UnclUp);
	tree->SetBranchAddress("MET_pt_UnclDown",&MET_pt_UnclDown);
	tree->SetBranchAddress("MET_phi_UnclDown",&MET_phi_UnclDown);
	tree->SetBranchAddress("met_UnclX",&met_UnclX);
	tree->SetBranchAddress("met_UnclY",&met_UnclY);
	tree->SetBranchAddress("MET_T1Smear_pt",&MET_T1Smear_pt);
	tree->SetBranchAddress("MET_T1Smear_phi",&MET_T1Smear_phi);
	tree->SetBranchAddress("met",&met);
	tree->SetBranchAddress("metphi",&metphi);
	tree->SetBranchAddress("metNoCor",&metNoCor);
	tree->SetBranchAddress("metphiNoCor",&metphiNoCor);
	tree->SetBranchAddress("metNoTauES",&metNoTauES);
	tree->SetBranchAddress("metphiNoTauES",&metphiNoTauES);
	tree->SetBranchAddress("metcov00",&metcov00);
	tree->SetBranchAddress("metcov01",&metcov01);
	tree->SetBranchAddress("metcov10",&metcov10);
	tree->SetBranchAddress("metcov11",&metcov11);
	tree->SetBranchAddress("isTrig_2",&isTrig_2);
	tree->SetBranchAddress("isTrig_1",&isTrig_1);
	tree->SetBranchAddress("isDoubleTrig",&isDoubleTrig);
	tree->SetBranchAddress("njets",&njets);
	tree->SetBranchAddress("nbtagL",&nbtagL);
	tree->SetBranchAddress("nbtagM",&nbtagM);
	tree->SetBranchAddress("nbtagT",&nbtagT);
	tree->SetBranchAddress("HTXS_Higgs_cat",&HTXS_Higgs_cat);
	tree->SetBranchAddress("HTXS_Higgs_pt",&HTXS_Higgs_pt);
	tree->SetBranchAddress("jflavour",jflavour);
	tree->SetBranchAddress("jeta",jeta);
	tree->SetBranchAddress("jpt",jpt);
	tree->SetBranchAddress("btagDeep",btagDeep);

//  This is the loop skeleton
// To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname
	//tree->SetBranchStatus("*",0);
	//tree->SetBranchStatus("mll",1);
}
