#include <TTree.h>
#include <TH1F.h>
#include <TCanvas.h>

//////////////////////////////////////////////////////////
// Made using tree->MakeClass("MyBranch"); Creates MyBranch.C and MyBranch.h 
//This file has been automatically generated 
//  (Mon Dec 11 17:10:06 2023 by ROOT version6.26/10)
//from TTree tree/Output tree
//found on file: ZZTo4L_test.root
//////////////////////////////////////////////////////////
   // Declaration of leaf types
   Int_t           nElectron;
   Int_t           nMuon;
   Int_t           nTau;
   Int_t           evt;
   Int_t           nPU;
   Int_t           nPUEOOT;
   Int_t           nPULOOT;
   Double_t        nPUtrue;
   Int_t           nPV;
   Int_t           nPVGood;
   Int_t           cat;
   Int_t           gen_cat;
   Double_t        brWeight;
   Double_t        weight;
   Double_t        weightPU;
   Double_t        weightPUtrue;
   Double_t        weightPUtruejson;
   Double_t        weightPUtruejson_up;
   Double_t        weightPUtruejson_down;
   Double_t        LHEweight;
   Int_t           LHE_Njets;
   Double_t        Generator_weight;
   Int_t           electronTriggerWord;
   Int_t           muonTriggerWord;
   Int_t           whichTriggerWord;
   Int_t           whichTriggerWordSubL;
   Int_t           nLooseElectron;
   Int_t           nLooseMuon;
   Int_t           nLooseTau;
   Double_t        mDCH1_sv;
   Double_t        mtDCH1_sv;
   Double_t        mDCH2_sv;
   Double_t        mtDCH2_sv;
   Double_t        mDCH1_sv4;
   Double_t        mtDCH1_sv4;
   Double_t        mDCH2_sv4;
   Double_t        mtDCH2_sv4;
   Double_t        L1PreFiringWeight_Nom;
   Double_t        L1PreFiringWeight_Up;
   Double_t        L1PreFiringWeight_Down;
   Double_t        MET_pt_UnclUp;
   Double_t        MET_phi_UnclUp;
   Double_t        MET_pt_UnclDown;
   Double_t        MET_phi_UnclDown;
   Double_t        met_UnclX;
   Double_t        met_UnclY;
   Double_t        MET_T1Smear_pt;
   Double_t        MET_T1Smear_phi;
   Double_t        met;
   Double_t        metphi;
   Double_t        metNoCor;
   Double_t        metphiNoCor;
   Double_t        metNoTauES;
   Double_t        metphiNoTauES;
   Double_t        metcov00;
   Double_t        metcov01;
   Double_t        metcov10;
   Double_t        metcov11;
   Double_t        isTrig_2;
   Double_t        isTrig_1;
   Double_t        isDoubleTrig;
   Double_t        njets;
   Double_t        nbtagL;
   Double_t        nbtagM;
   Double_t        nbtagT;
   Double_t        pt_3_tr;
   Double_t        phi_3_tr;
   Double_t        eta_3_tr;
   Double_t        pt_4_tr;
   Double_t        phi_4_tr;
   Double_t        eta_4_tr;
   Double_t        m_1_tr;
   Double_t        pt_1_tr;
   Double_t        phi_1_tr;
   Double_t        eta_1_tr;
   Double_t        m_2_tr;
   Double_t        pt_2_tr;
   Double_t        phi_2_tr;
   Double_t        eta_2_tr;
   ULong64_t       run;
   Double_t        IDSF_1;
   Double_t        IDSF_2;
   Double_t        IDSF_3;
   Double_t        IDSF_4;
   Double_t        ISOSF_1;
   Double_t        ISOSF_2;
   Double_t        ISOSF_3;
   Double_t        ISOSF_4;
   Double_t        TrigSF_1;
   Double_t        TrigSF_2;
   Double_t        TrigSF_3;
   Double_t        TrigSF_4;
   Double_t        TauVsEleIDSF_1;
   Double_t        TauVsEleIDSF_2;
   Double_t        TauVsEleIDSF_3;
   Double_t        TauVsEleIDSF_4;
   Double_t        TauVsMuIDSF_1;
   Double_t        TauVsMuIDSF_2;
   Double_t        TauVsMuIDSF_3;
   Double_t        TauVsMuIDSF_4;
   Double_t        TauVsJetIDSF_1;
   Double_t        TauVsJetIDSF_2;
   Double_t        TauVsJetIDSF_3;
   Double_t        TauVsJetIDSF_4;
   Double_t        TauES_1;
   Double_t        TauES_2;
   Double_t        TauES_3;
   Double_t        TauES_4;
   Double_t        d0_1;
   Double_t        d0_2;
   Double_t        d0_3;
   Double_t        d0_4;
   Double_t        dZ_1;
   Double_t        dZ_2;
   Double_t        dZ_3;
   Double_t        dZ_4;
   Double_t        pt_1;
   Double_t        pt_2;
   Double_t        pt_3;
   Double_t        pt_4;
   Double_t        eta_1;
   Double_t        eta_2;
   Double_t        eta_3;
   Double_t        eta_4;
   Double_t        phi_1;
   Double_t        phi_2;
   Double_t        phi_3;
   Double_t        phi_4;
   Double_t        m_1;
   Double_t        m_2;
   Double_t        m_3;
   Double_t        m_4;
   Double_t        q_1;
   Double_t        q_2;
   Double_t        q_3;
   Double_t        q_4;
   Double_t        iso_1;
   Double_t        iso_2;
   Double_t        iso_3;
   Double_t        iso_4;
   Int_t genPartFlav_1, genPartFlav_2, genPartFlav_3, genPartFlav_4;
   vector<double>  *lpt;
   vector<double>  *leta;
   vector<double>  *lphi;
   vector<double>  *lmass;
   vector<int>     *lq;
   vector<int>     *lflavor;
   vector<double>  *liso;
   vector<double>  *ld0;
   vector<double>  *ldZ;
   vector<double>  *EleID;
   vector<double>  *EleID_WP90;
   vector<double>  *EleID_WPL;
   vector<int>     *MuID;
   vector<int>     *TauIDe;
   vector<int>     *TauIDm;
   vector<int>     *TauIDj;
   vector<int>     *decayMode;
   vector<int>     *gen_match;
   vector<int>     *GenPart_statusFlags;
   vector<int>     *GenPart_status;
   vector<double>  *LHEScaleWeights;

void MyBranch(TTree *tree)
{
   // The Init() function is called when the selector needs to initialize
   // a new tree or chain. Typically here the branch addresses and branch
   // pointers of the tree will be set.
   // It is normally not necessary to make changes to the generated
   // code, but the routine can be extended by the user if needed.
   // Init() will be called many times when running on PROOF
   // (once per file to be processed).

   // Set object pointer
   lpt = 0;
   leta = 0;
   lphi = 0;
   lmass = 0;
   lq = 0;
   lflavor = 0;
   liso = 0;
   ld0 = 0;
   ldZ = 0;
   EleID = 0;
   EleID_WP90 = 0;
   EleID_WPL = 0;
   MuID = 0;
   TauIDe = 0;
   TauIDm = 0;
   TauIDj = 0;
   decayMode = 0;
   gen_match = 0;
   GenPart_statusFlags = 0;
   GenPart_status = 0;
   LHEScaleWeights = 0;
   // Set branch addresses and branch pointers
   if (!tree) return;

   tree->SetBranchAddress("nElectron", &nElectron);
   tree->SetBranchAddress("nMuon", &nMuon);
   tree->SetBranchAddress("nTau", &nTau);
   tree->SetBranchAddress("evt", &evt);
   tree->SetBranchAddress("nPU", &nPU);
   tree->SetBranchAddress("nPUEOOT", &nPUEOOT);
   tree->SetBranchAddress("nPULOOT", &nPULOOT);
   tree->SetBranchAddress("nPUtrue", &nPUtrue);
   tree->SetBranchAddress("nPV", &nPV);
   tree->SetBranchAddress("nPVGood", &nPVGood);
   tree->SetBranchAddress("cat", &cat);
   tree->SetBranchAddress("gen_cat", &gen_cat);
   tree->SetBranchAddress("brWeight", &brWeight);
   tree->SetBranchAddress("weight", &weight);
   tree->SetBranchAddress("weightPU", &weightPU);
   tree->SetBranchAddress("weightPUtrue", &weightPUtrue);
   tree->SetBranchAddress("weightPUtruejson", &weightPUtruejson);
   tree->SetBranchAddress("weightPUtruejson_up", &weightPUtruejson_up);
   tree->SetBranchAddress("weightPUtruejson_down", &weightPUtruejson_down);
   tree->SetBranchAddress("LHEweight", &LHEweight);
   tree->SetBranchAddress("LHE_Njets", &LHE_Njets);
   tree->SetBranchAddress("Generator_weight", &Generator_weight);
   tree->SetBranchAddress("electronTriggerWord", &electronTriggerWord);
   tree->SetBranchAddress("muonTriggerWord", &muonTriggerWord);
   tree->SetBranchAddress("whichTriggerWord", &whichTriggerWord);
   tree->SetBranchAddress("whichTriggerWordSubL", &whichTriggerWordSubL);
   tree->SetBranchAddress("nLooseElectron", &nLooseElectron);
   tree->SetBranchAddress("nLooseMuon", &nLooseMuon);
   tree->SetBranchAddress("nLooseTau", &nLooseTau);
   tree->SetBranchAddress("mDCH1_sv", &mDCH1_sv);
   tree->SetBranchAddress("mtDCH1_sv", &mtDCH1_sv);
   tree->SetBranchAddress("mDCH2_sv", &mDCH2_sv);
   tree->SetBranchAddress("mtDCH2_sv", &mtDCH2_sv);
   tree->SetBranchAddress("mDCH1_sv4", &mDCH1_sv4);
   tree->SetBranchAddress("mtDCH1_sv4", &mtDCH1_sv4);
   tree->SetBranchAddress("mDCH2_sv4", &mDCH2_sv4);
   tree->SetBranchAddress("mtDCH2_sv4", &mtDCH2_sv4);
   tree->SetBranchAddress("L1PreFiringWeight_Nom", &L1PreFiringWeight_Nom);
   tree->SetBranchAddress("L1PreFiringWeight_Up", &L1PreFiringWeight_Up);
   tree->SetBranchAddress("L1PreFiringWeight_Down", &L1PreFiringWeight_Down);
   tree->SetBranchAddress("MET_pt_UnclUp", &MET_pt_UnclUp);
   tree->SetBranchAddress("MET_phi_UnclUp", &MET_phi_UnclUp);
   tree->SetBranchAddress("MET_pt_UnclDown", &MET_pt_UnclDown);
   tree->SetBranchAddress("MET_phi_UnclDown", &MET_phi_UnclDown);
   tree->SetBranchAddress("met_UnclX", &met_UnclX);
   tree->SetBranchAddress("met_UnclY", &met_UnclY);
   tree->SetBranchAddress("MET_T1Smear_pt", &MET_T1Smear_pt);
   tree->SetBranchAddress("MET_T1Smear_phi", &MET_T1Smear_phi);
   tree->SetBranchAddress("met", &met);
   tree->SetBranchAddress("metphi", &metphi);
   tree->SetBranchAddress("metNoCor", &metNoCor);
   tree->SetBranchAddress("metphiNoCor", &metphiNoCor);
   tree->SetBranchAddress("metNoTauES", &metNoTauES);
   tree->SetBranchAddress("metphiNoTauES", &metphiNoTauES);
   tree->SetBranchAddress("metcov00", &metcov00);
   tree->SetBranchAddress("metcov01", &metcov01);
   tree->SetBranchAddress("metcov10", &metcov10);
   tree->SetBranchAddress("metcov11", &metcov11);
   tree->SetBranchAddress("isTrig_2", &isTrig_2);
   tree->SetBranchAddress("isTrig_1", &isTrig_1);
   tree->SetBranchAddress("isDoubleTrig", &isDoubleTrig);
   tree->SetBranchAddress("njets", &njets);
   tree->SetBranchAddress("nbtagL", &nbtagL);
   tree->SetBranchAddress("nbtagM", &nbtagM);
   tree->SetBranchAddress("nbtagT", &nbtagT);
   tree->SetBranchAddress("pt_3_tr", &pt_3_tr);
   tree->SetBranchAddress("phi_3_tr", &phi_3_tr);
   tree->SetBranchAddress("eta_3_tr", &eta_3_tr);
   tree->SetBranchAddress("pt_4_tr", &pt_4_tr);
   tree->SetBranchAddress("phi_4_tr", &phi_4_tr);
   tree->SetBranchAddress("eta_4_tr", &eta_4_tr);
   tree->SetBranchAddress("m_1_tr", &m_1_tr);
   tree->SetBranchAddress("pt_1_tr", &pt_1_tr);
   tree->SetBranchAddress("phi_1_tr", &phi_1_tr);
   tree->SetBranchAddress("eta_1_tr", &eta_1_tr);
   tree->SetBranchAddress("m_2_tr", &m_2_tr);
   tree->SetBranchAddress("pt_2_tr", &pt_2_tr);
   tree->SetBranchAddress("phi_2_tr", &phi_2_tr);
   tree->SetBranchAddress("eta_2_tr", &eta_2_tr);
   tree->SetBranchAddress("run", &run);
   tree->SetBranchAddress("IDSF_1", &IDSF_1);
   tree->SetBranchAddress("IDSF_2", &IDSF_2);
   tree->SetBranchAddress("IDSF_3", &IDSF_3);
   tree->SetBranchAddress("IDSF_4", &IDSF_4);
   tree->SetBranchAddress("ISOSF_1", &ISOSF_1);
   tree->SetBranchAddress("ISOSF_2", &ISOSF_2);
   tree->SetBranchAddress("ISOSF_3", &ISOSF_3);
   tree->SetBranchAddress("ISOSF_4", &ISOSF_4);
   tree->SetBranchAddress("TrigSF_1", &TrigSF_1);
   tree->SetBranchAddress("TrigSF_2", &TrigSF_2);
   tree->SetBranchAddress("TrigSF_3", &TrigSF_3);
   tree->SetBranchAddress("TrigSF_4", &TrigSF_4);
   tree->SetBranchAddress("TauVsEleIDSF_1", &TauVsEleIDSF_1);
   tree->SetBranchAddress("TauVsEleIDSF_2", &TauVsEleIDSF_2);
   tree->SetBranchAddress("TauVsEleIDSF_3", &TauVsEleIDSF_3);
   tree->SetBranchAddress("TauVsEleIDSF_4", &TauVsEleIDSF_4);
   tree->SetBranchAddress("TauVsMuIDSF_1", &TauVsMuIDSF_1);
   tree->SetBranchAddress("TauVsMuIDSF_2", &TauVsMuIDSF_2);
   tree->SetBranchAddress("TauVsMuIDSF_3", &TauVsMuIDSF_3);
   tree->SetBranchAddress("TauVsMuIDSF_4", &TauVsMuIDSF_4);
   tree->SetBranchAddress("TauVsJetIDSF_1", &TauVsJetIDSF_1);
   tree->SetBranchAddress("TauVsJetIDSF_2", &TauVsJetIDSF_2);
   tree->SetBranchAddress("TauVsJetIDSF_3", &TauVsJetIDSF_3);
   tree->SetBranchAddress("TauVsJetIDSF_4", &TauVsJetIDSF_4);
   tree->SetBranchAddress("TauES_1", &TauES_1);
   tree->SetBranchAddress("TauES_2", &TauES_2);
   tree->SetBranchAddress("TauES_3", &TauES_3);
   tree->SetBranchAddress("TauES_4", &TauES_4);
   tree->SetBranchAddress("d0_1", &d0_1);
   tree->SetBranchAddress("d0_2", &d0_2);
   tree->SetBranchAddress("d0_3", &d0_3);
   tree->SetBranchAddress("d0_4", &d0_4);
   tree->SetBranchAddress("dZ_1", &dZ_1);
   tree->SetBranchAddress("dZ_2", &dZ_2);
   tree->SetBranchAddress("dZ_3", &dZ_3);
   tree->SetBranchAddress("dZ_4", &dZ_4);
   tree->SetBranchAddress("pt_1", &pt_1);
   tree->SetBranchAddress("pt_2", &pt_2);
   tree->SetBranchAddress("pt_3", &pt_3);
   tree->SetBranchAddress("pt_4", &pt_4);
   tree->SetBranchAddress("eta_1", &eta_1);
   tree->SetBranchAddress("eta_2", &eta_2);
   tree->SetBranchAddress("eta_3", &eta_3);
   tree->SetBranchAddress("eta_4", &eta_4);
   tree->SetBranchAddress("phi_1", &phi_1);
   tree->SetBranchAddress("phi_2", &phi_2);
   tree->SetBranchAddress("phi_3", &phi_3);
   tree->SetBranchAddress("phi_4", &phi_4);
   tree->SetBranchAddress("m_1", &m_1);
   tree->SetBranchAddress("m_2", &m_2);
   tree->SetBranchAddress("m_3", &m_3);
   tree->SetBranchAddress("m_4", &m_4);
   tree->SetBranchAddress("q_1", &q_1);
   tree->SetBranchAddress("q_2", &q_2);
   tree->SetBranchAddress("q_3", &q_3);
   tree->SetBranchAddress("q_4", &q_4);
   tree->SetBranchAddress("iso_1", &iso_1);
   tree->SetBranchAddress("iso_2", &iso_2);
   tree->SetBranchAddress("iso_3", &iso_3);
   tree->SetBranchAddress("iso_4", &iso_4);
   tree->SetBranchAddress("genPartFlav_1", &genPartFlav_1);
   tree->SetBranchAddress("genPartFlav_2", &genPartFlav_2);
   tree->SetBranchAddress("genPartFlav_3", &genPartFlav_3);
   tree->SetBranchAddress("genPartFlav_4", &genPartFlav_4);
   tree->SetBranchAddress("lpt", &lpt);
   tree->SetBranchAddress("leta", &leta);
   tree->SetBranchAddress("lphi", &lphi);
   tree->SetBranchAddress("lmass", &lmass);
   tree->SetBranchAddress("lq", &lq);
   tree->SetBranchAddress("lflavor", &lflavor);
   tree->SetBranchAddress("liso", &liso);
   tree->SetBranchAddress("ld0", &ld0);
   tree->SetBranchAddress("ldZ", &ldZ);
   tree->SetBranchAddress("EleID", &EleID);
   tree->SetBranchAddress("EleID_WP90", &EleID_WP90);
   tree->SetBranchAddress("EleID_WPL", &EleID_WPL);
   tree->SetBranchAddress("MuID", &MuID);
   tree->SetBranchAddress("TauIDe", &TauIDe);
   tree->SetBranchAddress("TauIDm", &TauIDm);
   tree->SetBranchAddress("TauIDj", &TauIDj);
   tree->SetBranchAddress("decayMode", &decayMode);
   tree->SetBranchAddress("gen_match", &gen_match);
   tree->SetBranchAddress("GenPart_statusFlags", &GenPart_statusFlags);
   tree->SetBranchAddress("GenPart_status", &GenPart_status);
   tree->SetBranchAddress("LHEScaleWeights", &LHEScaleWeights);
	/*tree->SetBranchAddress("nupt_1",&nupt_1);
	tree->SetBranchAddress("nupt_2",&nupt_2);
	tree->SetBranchAddress("nupt_3",&nupt_3);
	tree->SetBranchAddress("nupt_4",&nupt_4);
	tree->SetBranchAddress("nueta_1",&nueta_1);
	tree->SetBranchAddress("nueta_2",&nueta_2);
	tree->SetBranchAddress("nueta_3",&nueta_3);
	tree->SetBranchAddress("nueta_4",&nueta_4);
	tree->SetBranchAddress("nuphi_1",&nuphi_1);
	tree->SetBranchAddress("nuphi_2",&nuphi_2);
	tree->SetBranchAddress("nuphi_3",&nuphi_3);
	tree->SetBranchAddress("nuphi_4",&nuphi_4);
	tree->SetBranchAddress("nuM_1",&nuM_1);
	tree->SetBranchAddress("nuM_2",&nuM_2);
	tree->SetBranchAddress("nuM_3",&nuM_3);
	tree->SetBranchAddress("nuM_4",&nuM_4);*/

//  This is the loop skeleton
// To read only selected branches, Insert statements like:
// tree->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname
	//tree->SetBranchStatus("*",0);
	//tree->SetBranchStatus("mll",1);
}
